dataset = 'up'
k = 10
drop_cols = ['B invariant mass', 'dimuon-system invariant mass',
             'Magnet polarity', 'Event ID']

important_cols = ['B transverse momentum', 'Kaon transverse momentum',
                  'Opposite-sign muon transverse momentum',
                  'Dimuon-system transverse momentum',
                  'Topology BDT', 'B vertex chi2',
                  'B flight distance significance', 'B impact parameter chi2',
                  'Kaon impact parameter chi2',
                  'Muon 1 impact parameter chi2',
                  'Muon 2 impact parameter chi2',
                  'Dimuon parameter chi2', 'Mu flight distance significance',
                  'Kaon muon minimum impact parameter chi2', 'B cos(theta) angle momentum frame']

drop_cols_old = [
    'B decay vertex x position', 'B decay vertex y position', 'B decay vertex z position',
    'B impact parameter wrt primary vertex', 'B flight distance wrt primary vertex',
    'B magnitude of momentum', 'B 4-momentum energy component', 'B 4-momentum x component',
    'B 4-momentum y component', 'B 4-momentum z component', 'B invariant mass',
    'B assumed particle type', 'B lifetime', 'Isolation: Charged cone angle',
    'Isolation: Charged cone number of particles contained',
    'Isolation: Charged cone eta difference between cone momentum and B',
    'Isolation: Charged cone phi difference between cone momentum and B',
    'Isolation: Charged cone ratio of B momentum and B+cone momentum all in transverse plane',
    'Isolation: Charged cone 4-momentum of max-PT object energy component',
    'Isolation: Charged cone 4-momentum of max-PT object transverse component',
    'Isolation: Charged cone 4-momentum of max-PT object x component',
    'Isolation: Charged cone 4-momentum of max-PT object y component',
    'Isolation: Charged cone 4-momentum of max-PT object z component',
    'Isolation: Charged cone charge of max-PT object', 'Isolation: Charged cone momentum sum x component',
    'Isolation: Charged cone momentum sum y component', 'Isolation: Charged cone momentum sum z component',
    'Isolation: Charged cone asymmetry between cone momentum and B momentum',
    'Isolation: Charged cone asymmetry between cone momentum and B momentum transverse component',
    'Isolation: Charged cone asymmetry between cone momentum and B momentum x component',
    'Isolation: Charged cone asymmetry between cone momentum and B momentum y component',
    'Isolation: Charged cone asymmetry between cone momentum and B momentum z component',
    'Isolation: Charged cone scalar sum of PT', 'Isolation: Charged cone vector sum of PT',
    'Isolation: Neutral cone angle', 'Isolation: Neutral cone number of particles containted',
    'Isolation: Neutral cone eta difference between cone momentum and B',
    'Isolation: Neutral cone phi difference between cone momentum and B',
    'Isolation: Neutral cone ratio of B momentum and B+cone momentum all in transverse plane',
    'Isolation: Neutral cone 4-momentum of max-PT object transverse component',
    'Isolation: Neutral cone 4-momentum of max-PT object x component',
    'Isolation: Neutral cone 4-momentum of max-PT object y component',
    'Isolation: Neutral cone 4-momentum of max-PT object z component',
    'Isolation: Neutral cone momentum sum x component', 'Isolation: Neutral cone momentum sum y component',
    'Isolation: Neutral cone momentum sum z component', 'Isolation: Neutral cone asymmetry between cone momentum and B momentum',
    'Isolation: Neutral cone asymmetry between cone momentum and B momentum transverse component',
    'Isolation: Neutral cone asymmetry between cone momentum and B momentum x component',
    'Isolation: Neutral cone asymmetry between cone momentum and B momentum y component',
    'Isolation: Neutral cone asymmetry between cone momentum and B momentum z component',
    'Isolation: Neutral cone scalar sum of PT', 'Isolation: Neutral cone vector sum of PT',
    'Isolation: ML output of best fitting extra track', 'Isolation: B mass if one extra track (best fit) is added',
    'Isolation: B mass if two extra tracks (best fits) are added', 'Isolation: B vertex delta chi2 adding one extra track (best fit)',
    'Isolation: B vertex delta chi2 adding two extra tracks (best fits)', 'Isolation: B vertex number of well fitting additional tracks',
    'dimuon-system decay vertex x position', 'dimuon-system decay vertex y position',
    'dimuon-system decay vertex z position', 'dimuon-system impact parameter wrt primary vertex',
    'dimuon-system impact parameter chi2 wrt primary vertex', 'dimuon-system flight distance wrt primary vertex',
    'dimuon-system cos(angle) between line-of-flight from primary vertex and momentum',
    'dimuon-system flight distance wrt B-decay vertex', 'dimuon-system flight distance chi2 wrt B-decay vertex',
    'dimuon-system cos(angle) between line-of-flight from B-decay vertex and momentum',
    'dimuon-system magnitude of momentum', 'dimuon-system 4-momentum energy component',
    'dimuon-system 4-momentum x component', 'dimuon-system 4-momentum y component',
    'dimuon-system 4-momentum z component', 'dimuon-system invariant mass', 'dimuon-system lifetime',
    'Same-sign muon impact parameter wrt primary vertex', 'Same-sign muon magnitude of momentum',
    'Same-sign muon 4-momentum energy component', 'Same-sign muon 4-momentum x component',
    'Same-sign muon 4-momentum y component', 'Same-sign muon 4-momentum z component',
    'Same-sign muon invariant mass', 'Same-sign muon assumed particle type',
    'Same-sign muon PID NN score for electron hypothesis', 'Same-sign muon PID NN score for kaon hypothesis',
    'Same-sign muon PID NN score for proton hypothesis', 'Same-sign muon PID NN score for pion hypothesis',
    'Same-sign muon PID NN score for muon hypothesis', 'Same-sign muon PID NN score for ghost-track hypothesis',
    'Same-sign muon PID muon system flag', 'Opposite-sign muon impact parameter wrt primary vertex',
    'Opposite-sign muon magnitude of momentum', 'Opposite-sign muon 4-momentum energy component',
    'Opposite-sign muon 4-momentum x component', 'Opposite-sign muon 4-momentum y component',
    'Opposite-sign muon 4-momentum z component', 'Opposite-sign muon invariant mass',
    'Opposite-sign muon assumed particle type', 'Opposite-sign muon PID NN score for electron hypothesis',
    'Opposite-sign muon PID NN score for kaon hypothesis', 'Opposite-sign muon PID NN score for proton hypothesis',
    'Opposite-sign muon PID NN score for pion hypothesis', 'Opposite-sign muon PID NN score for muon hypothesis',
    'Opposite-sign muon PID NN score for ghost-track hypothesis', 'Opposite-sign muon PID muon system flag',
    'Kaon impact parameter wrt primary vertex', 'Kaon magnitude of momentum',
    'Kaon 4-momentum energy component', 'Kaon 4-momentum x component', 'Kaon 4-momentum y component',
    'Kaon 4-momentum z component', 'Kaon invariant mass', 'Kaon assumed particle type',
    'Kaon PID NN score for electron hypothesis', 'Kaon PID NN score for kaon hypothesis',
    'Kaon PID NN score for proton hypothesis', 'Kaon PID NN score for pion hypothesis',
    'Kaon PID NN score for muon hypothesis', 'Kaon PID NN score for ghost-track hypothesis',
    'Kaon PID muon system flag', 'Magnet polarity', 'Number of reconstructed pp collision in event',
    'Number of reconstructed tracks in event', 'Candidate in event', 'Event ID'
]
