dataset = '2011'
k = 5
drop_cols = ['B invariant mass', 'dimuon-system invariant mass',
             'Magnet polarity', 'Event ID',
             #  'B assumed particle type',
             #  'Kaon assumed particle type',
             #  'Same-sign muon assumed particle type',
             #  'Opposite-sign muon assumed particle type',

             'Kaon PID NN score for electron hypothesis',
             'Kaon PID NN score for kaon hypothesis',
             'Kaon PID NN score for proton hypothesis',
             'Kaon PID NN score for pion hypothesis',
             'Kaon PID NN score for muon hypothesis',
             'Kaon PID NN score for ghost-track hypothesis',
             'Kaon PID muon system flag',
             'Same-sign muon PID NN score for electron hypothesis',
             'Same-sign muon PID NN score for kaon hypothesis',
             'Same-sign muon PID NN score for proton hypothesis',
             'Same-sign muon PID NN score for pion hypothesis',
             'Same-sign muon PID NN score for muon hypothesis',
             'Same-sign muon PID NN score for ghost-track hypothesis',
             'Same-sign muon PID muon system flag',
             'Opposite-sign muon PID NN score for electron hypothesis',
             'Opposite-sign muon PID NN score for kaon hypothesis',
             'Opposite-sign muon PID NN score for proton hypothesis',
             'Opposite-sign muon PID NN score for pion hypothesis',
             'Opposite-sign muon PID NN score for muon hypothesis',
             'Opposite-sign muon PID NN score for ghost-track hypothesis',
             'Opposite-sign muon PID muon system flag'
             ]
